// Articles module
export const ARTICLES_SERVICE_TOKEN = 'ARTICLES_SERVICE_TOKEN';
export const ARTICLES_REPOSITORY_TOKEN = 'ARTICLES_REPOSITORY_TOKEN';

// Auth module
export const AUTH_SERVICE_TOKEN = 'AUTH_SERVICE_TOKEN';
export const AUTH_REPOSITORY_TOKEN = 'AUTH_REPOSITORY_TOKEN';
